includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser.yaml

variables:
  main: "./cmd/soft"
  binary_name: soft
  description: "A personal key value store"
  github_url: "https://github.com/charmbracelet/soft-serve"
  maintainer: "Christian Rocha <christian@charm.sh>"
  brew_commit_author_name: "Christian Rocha"
  brew_commit_author_email: "christian@charm.sh"
